#!/bin/bash

MAKEMODE=$1
CURRENTDIR=${2:-`pwd`}
PROJECT=`basename $CURRENTDIR`
PARENTDIR=`dirname $CURRENTDIR`
BUILDDIR=$PARENTDIR/".build_"$PROJECT
PROJECTNAME=$PROJECT".ino"

usage() {
    echo "usage: $0 target [project-dir]"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

if [ ! -d "$CURRENTDIR" ]; then
    echo "$CURRENTDIR is not a directory"
    exit 1
fi

mkdir -p $BUILDDIR
ctags --language-force=c --exclude=$PROJECTNAME *.ino

# parse tags file and grab all the function headers
cat tags | grep -v '^!' | grep 'f$'| grep -o '/\^.*\$\/' | sed 's/\/^//' | sed 's/{.*}//' | sed 's/$\//;/' > $BUILDDIR/$PROJECTNAME

cat $PROJECT".ino" >> $BUILDDIR/$PROJECTNAME

for i in `find $CURRENTDIR -name "*.ino" -type f`
do
    if [[ `basename $i` != $PROJECTNAME ]]; then
        cat $i >> $BUILDDIR/$PROJECTNAME
    fi
done

cp $CURRENTDIR/Makefile $BUILDDIR/
rm tags

pushd $BUILDDIR
    make $MAKEMODE
popd

rm -rf $BUILDDIR
