#!/bin/bash

MAKEMODE=$1
CURRENTDIR=${2:-`pwd`}
PROJECT=`basename $CURRENTDIR`
PARENTDIR=`dirname $CURRENTDIR`
BUILDDIR=$PARENTDIR/".build_"$PROJECT
PROJECTNAME=$PROJECT".ino"

usage() {
    echo "usage: $0 target [project-dir]"
    echo "  (Note that there exists a special target 'compile' which just compiles"
    echo "   the code, which is what a bare 'make' would do with Arduino Makefile)"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

if [ "$MAKEMODE" == "compile" ]; then
    MAKEMODE=''
fi

if [ ! -d "$CURRENTDIR" ]; then
    echo "$CURRENTDIR is not a directory"
    exit 1
fi

command -v ctags >/dev/null 2>&1 || {
    echo >&2 "ctags is required for building your project. Please install it!"
    exit 1
}

ctags --language-force=c --exclude=$PROJECTNAME *.ino
if ! grep -q "$(printf '_TAG_PROGRAM_NAME\tExuberant Ctags\t//')" tags; then
    echo >&2 "ctags generated output not compatible with ambu."
    echo >&2 -n "Please install exuberant-ctags from repos or use this link:"
    echo >&2 "http://ctags.sourceforge.net/"
    exit 1
fi

mkdir -p $BUILDDIR

# Copy h|c|cpp files
find $CURRENTDIR -regex '.*.\(h\|c\|cpp\)$' -printf "%P\n" |
    xargs -I{} cp --parents "{}" $BUILDDIR

# parse tags file and grab all the function headers
cat tags | grep -v '^!' | grep 'f$'| grep -o '/\^.*\$\/' | sed 's/\/^//' |
    sed 's/{.*}//' | sed 's/$\//;/' > $BUILDDIR/$PROJECTNAME

cat $PROJECT".ino" >> $BUILDDIR/$PROJECTNAME

for i in `find $CURRENTDIR -name "*.ino" -type f`
do
    if [[ `basename $i` != $PROJECTNAME ]]; then
        cat $i >> $BUILDDIR/$PROJECTNAME
    fi
done

cp $CURRENTDIR/Makefile $BUILDDIR/
rm tags

pushd $BUILDDIR
    make $MAKEMODE
popd

rm -rf $BUILDDIR
